### ISSUE TITLE
[Crash/Conflict] Incompatible with stacked flower mods / New Release issues

### ISSUE THREAD

**Issue by A5ho9999** [GalievDev/ManyFlowers#11]
Latest update is incompatible with https://modrinth.com/mod/stackable-flowers and/or https://modrinth.com/mod/bushier-flowers

Crashes when trying to place the Jack Flower, other flowers are fine (deadlocks the game)

```
java.lang.IllegalArgumentException: Cannot get property class_2758{name=flower_amount, clazz=class java.lang.Integer, values=[1, 2, 3, 4]} as it does not exist in Block{many_flowers:jack_flower}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2356.method_9530(class_2356.java:562)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at net.minecraft.class_3959$class_3960.get(class_3959.java:67)
	at net.minecraft.class_3959.method_17748(class_3959.java:40)
	at net.minecraft.class_1922.method_17743(class_1922.java:80)
	at net.minecraft.class_1922.method_17744(class_1922.java:193)
	at net.minecraft.class_1922.method_17742(class_1922.java:73)
	at net.minecraft.class_1297.method_5745(class_1297.java:1715)
	at net.minecraft.class_757.method_3190(class_757.java:652)
	at net.minecraft.class_757.method_3188(class_757.java:1067)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

- Autumn Asters & Velvets aren't affected by their config
- Zinnia has an incorrect double drop (drops when breaking one part, even in creative)

**Comment by syorito-hatsuki** [comment]
@A5ho9999 So. About Stackable Flowers... The reason for the crash is [TheCharlsen](https://github.com/TheCharlsen) shit code. He forced some overrides that gonna break all mods with non-primitive flowers, not only this mod.

The guy should rewrite mixin. Using correct ways for that.
https://github.com/TheCharlsen/StackableFlowers/blob/6acc4cb7d9f8d36cd7c6b8cba1c2f7f95c9e4561/src/main/java/com/sunnyspaceweather/mixin/FlowerBlockMixin.java#L20

**Comment by GalievDev** [comment]
Other problems will be fixed as soon as possible

**Comment by GalievDev** [comment]
Other problems will be fixed as soon as possible

**Comment by syorito-hatsuki** [comment]
- [x] ~~Crashes when trying to place the Jack Flower, other flowers are fine (deadlocks the game)~~ (Stackable Flowers Issue)
- [x] Autumn Asters & Velvets aren't affected by their config
- [x] Zinnia has an incorrect double drop (drops when breaking one part, even in creative)

**Comment by GalievDev** [comment]
https://modrinth.com/mod/many-flowers/version/OIIWERoL
