### ISSUE TITLE
Error loading the flower_encyclopedia recipe

### ISSUE THREAD

**Issue by closingin** [GalievDev/ManyFlowers#14]
Hello there,

I'm trying to run a Fabric 1.20.4 server with your mod, but I get this error everytime :

```
[09:15:32] [main/ERROR]: Parsing error loading recipe many_flowers:flower_encyclopedia
com.google.gson.JsonParseException: Unknown registry key in ResourceKey[minecraft:root / minecraft:recipe_serializer]: patchouli:shapeless_book_recipe
	at net.minecraft.class_156.method_47526(class_156.java:1005) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:932) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:178) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
[09:15:32] [main/INFO]: Loaded 7 recipes
```

Is it safe to ignore?

Best.

**Comment by GalievDev** [comment]
Hi. Yes it is safe to ignore, it was a recipe for a patchouli book that I forgot to remove.
