### ISSUE TITLE
[Fabric 1.21] Crashes after singleplayer button is clicked

### ISSUE THREAD

**Issue by Poopooracoocoo** [GalievDev/ManyFlowers#16]
Registry errors

### Crash report

[crash-2024-06-29_16.48.15-client.txt](https://github.com/user-attachments/files/16039080/crash-2024-06-29_16.48.15-client.txt)

### Log

[latest.log](https://github.com/user-attachments/files/16039079/latest.log)

<details><summary>Details</summary>

```
[16:47:13] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[16:47:13] [main/WARN]: Warnings were found!
 - Mod 'ManyFlowers' (many_flowers) 1.21-1.0 recommends version 7.0.1 or later of modmenu, which is missing!
	 - You should install version 7.0.1 or later of modmenu for the optimal experience.
 - Mod 'ManyFlowers' (many_flowers) 1.21-1.0 recommends version 1.21.1-81-FABRIC or later of patchouli, which is missing!
	 - You should install version 1.21.1-81-FABRIC or later of patchouli for the optimal experience.
[16:47:13] [main/INFO]: Loading 56 mods:
	- cloth-config 15.0.127
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.100.4+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.48+f71b366fd1
	   |-- fabric-command-api-v2 2.2.27+6a6dfa19d1
	   |-- fabric-commands-v0 0.2.65+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.15+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.3.2+78017270d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.9+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8cd1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.11+6573ed8cd1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.23+78017270d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.70+df3654b3d1
	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5+78017270d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.80+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- many_flowers 1.21-1.0
	   \-- ducky-updater-lib 2023.10.1
	- minecraft 1.21
[16:47:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/anon/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:47:13] [main/INFO]: Compatibility level set to JAVA_17
[16:47:16] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[16:47:18] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 622 milliseconds
[16:47:36] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:47:36] [Render thread/INFO]: Setting user: Anon
[16:47:38] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[16:47:39] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[16:47:42] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, cloth-config, ducky-updater-lib, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, many_flowers
[16:47:43] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[16:47:44] [Worker-Main-5/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[16:47:46] [Worker-Main-6/WARN]: Unable to load model: 'many_flowers:item/hemlock' referenced from: many_flowers:item/hemlock: java.io.FileNotFoundException: many_flowers:models/item/hemlock.json
[16:47:47] [Worker-Main-6/WARN]: Missing textures in model many_flowers:jack_flower#lit=true:
    minecraft:textures/atlas/blocks.png:minecraft:block/grass
[16:47:47] [Worker-Main-6/WARN]: Missing textures in model many_flowers:jack_flower#inventory:
    minecraft:textures/atlas/blocks.png:minecraft:block/grass
[16:47:47] [Worker-Main-6/WARN]: Missing textures in model many_flowers:jack_flower#lit=false:
    minecraft:textures/atlas/blocks.png:minecraft:block/grass
[16:47:48] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[16:47:48] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[16:47:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[16:47:49] [Render thread/INFO]: Sound engine started
[16:47:49] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:47:49] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[16:47:49] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:47:49] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:47:49] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[16:47:49] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[16:47:49] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:47:49] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:47:49] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:47:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[16:47:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:47:50] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:47:50] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[16:47:50] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[16:47:51] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[16:48:14] [Render thread/ERROR]: Registry loading errors:
> Errors in registry minecraft:worldgen/placed_feature:
>> Errors in element many_flowers:velvets_placed:
java.lang.IllegalStateException: Failed to parse many_flowers:worldgen/placed_feature/velvets_placed.json from pack many_flowers
	at net.minecraft.class_7655.method_45122(class_7655.java:251)
	at net.minecraft.class_7655$class_9158.method_56520(class_7655.java:96)
	at net.minecraft.class_7655.method_56514(class_7655.java:151)
	at net.minecraft.class_7655.method_45120(class_7655.java:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_7655.method_45121(class_7655.java:164)
	at net.minecraft.class_7655.mixinextras$bridge$method_45121$31(class_7655.java)
	at net.minecraft.class_7655.wrapOperation$zik000$fabric-registry-sync-v0$wrapIsServerCall(class_7655.java:556)
	at net.minecraft.class_7655.mixinextras$bridge$wrapOperation$zik000$fabric-registry-sync-v0$wrapIsServerCall$34(class_7655.java)
	at net.minecraft.class_7655.wrapOperation$zko000$fabric-resource-conditions-api-v1$captureRegistries(class_7655.java:1057)
	at net.minecraft.class_7655.method_56515(class_7655.java:151)
	at net.minecraft.class_7237.method_45142(class_7237.java:62)
	at net.minecraft.class_7237.method_45143(class_7237.java:66)
	at net.minecraft.class_7237.method_42098(class_7237.java:32)
	at net.minecraft.class_525.method_31130(class_525.java:310)
	at net.minecraft.class_526.method_19944(class_526.java:54)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184)
	at net.minecraft.class_310.method_1523(class_310.java:1310)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IllegalStateException: Failed to parse either. First: Not a number: {"type":"minecraft:uniform","value":{"max_inclusive":4,"min_inclusive":0}}; Second: No key max_inclusive in MapLike[{"type":"minecraft:uniform","value":{"max_inclusive":4,"min_inclusive":0}}]; No key min_inclusive in MapLike[{"type":"minecraft:uniform","value":{"max_inclusive":4,"min_inclusive":0}}]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
	at net.minecraft.class_7655.method_56915(class_7655.java:231)
	at net.minecraft.class_7655.method_45122(class_7655.java:249)
	... 38 more

[16:48:15] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Failed to load registries due to above errors
	at net.minecraft.class_7655.method_45121(class_7655.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.mixinextras$bridge$method_45121$31(class_7655.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.wrapOperation$zik000$fabric-registry-sync-v0$wrapIsServerCall(class_7655.java:556) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.mixinextras$bridge$wrapOperation$zik000$fabric-registry-sync-v0$wrapIsServerCall$34(class_7655.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.wrapOperation$zko000$fabric-resource-conditions-api-v1$captureRegistries(class_7655.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_7655.method_56515(class_7655.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_45142(class_7237.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_45143(class_7237.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_7237.method_42098(class_7237.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_31130(class_525.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_526.method_19944(class_526.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 17 more
``` 

</details>

**Comment by GalievDev** [comment]
Fixed - https://modrinth.com/mod/many-flowers/version/QNAwC2gq
