### ISSUE TITLE
Stackoverflow

### ISSUE THREAD

**Issue by A5ho9999** [GalievDev/ManyFlowers#4]
Getting overflow error on a server Fabric 1.20.1

```
Caused by: java.lang.StackOverflowError
	at net.valion.manyflowers.helpers.WorldsHelper.isEmpty(WorldsHelper.java:53) ~[ManyFlowers-1.20.1-1.0.jar:?]
	at net.valion.manyflowers.helpers.WorldsHelper.isSafe(WorldsHelper.java:49) ~[ManyFlowers-1.20.1-1.0.jar:?]
	at net.valion.manyflowers.helpers.WorldsHelper.safeCheck(WorldsHelper.java:38) ~[ManyFlowers-1.20.1-1.0.jar:?]
	at net.valion.manyflowers.helpers.WorldsHelper.safeCheck(WorldsHelper.java:43) ~[ManyFlowers-1.20.1-1.0.jar:?]
	at net.valion.manyflowers.helpers.WorldsHelper.safeCheck(WorldsHelper.java:43) ~[ManyFlowers-1.20.1-1.0.jar:?]

**Comment by GalievDev** [comment]
Thank you for information! Problem solving in progress. All be done in next update.

**Comment by GalievDev** [comment]
FIxed - https://modrinth.com/mod/many-flowers/version/1.20-1.1

**Comment by A5ho9999** [comment]
Curious if this would also fix Root of the worlds randomly teleporting players when stepped on?

nevermind, realised this was a config.
